import { Car, Zap, Cpu, ShieldCheck, Code2, Network, Package } from "lucide-react";

export const expertises = [
  {
    slug: "mobilite-intelligente",
    number: "01",
    icon: Car,
    title: "Mobilité intelligente & Systèmes de transport",
    shortTitle: "Mobilité intelligente",
    desc: "Solutions intégrées pour optimiser la fluidité du trafic, moderniser les axes autoroutiers et automatiser la collecte des redevances.",
    points: [
      "Systèmes de péage automatisé et barrières haute vélocité",
      "Péage en flux libre (Free Flow) multi-voies sans arrêt",
      "Lecture automatique des plaques d'immatriculation (ANPR / LPR)",
      "Gestion intelligente des parkings et guidage à la place",
      "Systèmes de pesage dynamique en marche (WIM)",
      "Plateformes de gestion centralisée et sécurisée des recettes",
    ],
  },
  {
    slug: "infrastructures-electriques",
    number: "02",
    icon: Zap,
    title: "Infrastructures électriques & Énergie",
    shortTitle: "Infrastructures électriques",
    desc: "Conception, fiabilisation et déploiement de réseaux de distribution électrique et de secours pour sites stratégiques.",
    points: [
      "Courants Forts (CFO) : Postes HTA/BT, TGBT et armoires de distribution",
      "Courants Faibles (CFA) : Câblage structuré cuivre et fibre optique",
      "Secours énergétique : Onduleurs modulaires (UPS) et groupes électrogènes",
      "Installations solaires photovoltaïques et hybrides connectées",
      "Audit d'efficacité énergétique et qualité des réseaux électriques",
      "Protection contre la foudre et mise à la terre normalisée",
    ],
  },
  {
    slug: "automatisation-supervision",
    number: "03",
    icon: Cpu,
    title: "Automatisation & Supervision industrielle",
    shortTitle: "Automatisation & SCADA",
    desc: "Contrôle-commande temps réel et monitoring centralisé pour infrastructures critiques et unités de production.",
    points: [
      "Automates programmables industriels (PLC / API) multimarques",
      "Systèmes de supervision et acquisition de données (SCADA / IHM)",
      "Télégestion, télémétrie et protocoles IoT industriels (Modbus, OPC UA)",
      "Régulation thermique, GTB/GTC (Gestion Technique de Bâtiment)",
      "Hypervision unifiée des installations multi-sites",
      "Maintenance prédictive et alertes automatisées en temps réel",
    ],
  },
  {
    slug: "surete-securite-incendie",
    number: "04",
    icon: ShieldCheck,
    title: "Sûreté électronique & Sécurité incendie",
    shortTitle: "Sûreté électronique",
    desc: "Dispositifs technologiques de haute sécurité garantissant l'intégrité des personnes, des biens et des périmètres sensibles.",
    points: [
      "Vidéosurveillance IP haute définition avec analyse vidéo IA",
      "Contrôle d'accès biométrique, badges RFID et tourniquets sécurisés",
      "Détection intrusion périmétrique et clôtures instrumentées",
      "Systèmes de Sécurité Incendie (SSI) adressables certifiés",
      "Extinction automatique (gaz, brouillard d'eau, sprinklers)",
      "Postes de Commandement et de Sécurité (PCS) centralisés",
    ],
  },
  {
    slug: "developpement-applications",
    number: "05",
    icon: Code2,
    title: "Développement d'applications",
    shortTitle: "Développement d'applications",
    desc: "Des applications métier et plateformes web conçues pour piloter vos opérations et améliorer l'expérience de vos utilisateurs.",
    points: [
      "Applications web et mobiles sur mesure",
      "Portails métiers et tableaux de bord de pilotage",
      "Intégration d'API et interconnexion des systèmes",
      "Développement sécurisé et maintenance évolutive",
    ],
  },
  {
    slug: "reseau-informatique",
    number: "06",
    icon: Network,
    title: "Réseau informatique & Télécoms",
    shortTitle: "Réseau informatique",
    desc: "Des architectures réseau robustes, sécurisées et dimensionnées pour assurer la continuité de vos activités.",
    points: [
      "Conception et déploiement de réseaux LAN, WAN et Wi-Fi",
      "Fibre optique, câblage structuré et baies informatiques",
      "Sécurisation réseau, pare-feu et accès distants",
      "Supervision, maintenance et optimisation des infrastructures",
    ],
  },
  {
    slug: "fournitures-materiels",
    number: "07",
    icon: Package,
    title: "Fournitures & Matériels",
    shortTitle: "Fournitures",
    desc: "Approvisionnement de matériels technologiques et industriels sélectionnés pour répondre aux exigences de vos projets.",
    points: [
      "Équipements informatiques, réseau et télécoms",
      "Matériels de vidéosurveillance et contrôle d'accès",
      "Automates, capteurs et équipements d'instrumentation",
      "Onduleurs, armoires et accessoires électriques",
    ],
  },
];

export type Expertise = (typeof expertises)[number];
